# Este es el archivo de configuraci칩n de Netlify.

[build]
  # Directorio que se va a desplegar (tu aplicaci칩n de React)
  publish = "dist"
  # Comando para construir tu aplicaci칩n
  command = "npm run build"

[functions]
  # Directorio donde Netlify encontrar치 las funciones de backend
  directory = "netlify/functions"
